### ISSUE TITLE
Support for SIARD 2.2?

### ISSUE THREAD

**Issue by oschihin** [keeps/dbptk-desktop#52]
Hi
When opening a SIARD file I get the following error message: `Could not import the metadata to the Solr instance. caused by ModuleException: The metadata.xml file could not be read. caused by UnmarshalException: unerwartetes Element (URI:"http://www.bar.admin.ch/xmlns/siard/2/metadata.xsd", lokal:"siardArchive"). Erwartete Elemente sind <{http://www.bar.admin.ch/xmlns/siard/1.0/metadata.xsd}siardArchive>`
Does this mean DBPTK only supports SIARD up to version 1.0, or at least not 2.2
When opening this SIARD with SIARD suite 2.2.141, it works and shows version 2.2

**Comment by luis100** [comment]
Hello, DBPTK currently support SIARD 2.1, and not SIARD 2.2. Work for supporting SIARD 2.2 is ongoing
